apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-k8s-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-k8s-app
  template:
    metadata:
      labels:
        app: flask-k8s-app
    spec:
      containers:
      - name: flask-container
        image: gcr.io/kubernetes-deployment-462514/flask-k8s-app:latest
        ports:
        - containerPort: 8080

